# Generated by Django 6.0.3 on 2026-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user_count", models.PositiveIntegerField()),
                ("event_count", models.PositiveIntegerField()),
                ("edited_events", models.PositiveIntegerField()),
                ("cancelled_events", models.PositiveIntegerField()),
            ],
        ),
    ]
