# Generated by Django 6.0.3 on 2026-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
