# Generated by Django 6.0.3 on 2026-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_botstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
