# Generated by Django 6.0.3 on 2026-03-19 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_telegramuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_events",
                to="events.telegramuser",
            ),
        ),
    ]
