# Generated by Django 6.0.3 on 2026-03-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_events", models.IntegerField(default=0)),
                ("edited_events", models.IntegerField(default=0)),
                ("cancelled_events", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="events.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика пользователя",
                "verbose_name_plural": "Статистика пользователей",
            },
        ),
    ]
