# Generated by Django 6.0.3 on 2026-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_userstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичное"),
        ),
    ]
