FROM python:3.12-slim

WORKDIR /app

COPY . /app/

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app
ENV TELEGRAM_API_TOKEN=8634765574:AAEalcIcbAaYTRiIGKF7tftZxMTER_8rrPI

CMD ["python", "/app/bot.py"]