services:
  db:
    image: postgres:16
    container_name: bot_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  bot:
    build: .
    container_name: bot_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - web
    command: python bot.py
    volumes:
      - .:/app

volumes:
  postgres_data:
